### ISSUE TITLE
official Maven release

### ISSUE THREAD

**Issue by karussell** [bmwcarit/hmm-lib#4]
Would be super cool to have the 0.2.0 in maven central to be used [from us](https://github.com/graphhopper/map-matching/pull/49). For now we are using the cloned repo directly in our repo, which is kind of suboptimal.

**Comment by stefanholder** [comment]
Sure, I will take care of this.

**Comment by stefanholder** [comment]
I pushed some additional commits for version 0.2.0. Please note that I changed the package name, groupId and artifactId.

**Comment by karussell** [comment]
Thanks! Searching maven repo indicates this is not yet deployed there (you changed the artifactId to prepare this I guess :) ?)

BTW: via maven search I found this https://github.com/adrianulbona/hmm

**Comment by stefanholder** [comment]
Yes, changing the artifactId was done in preparation for Maven Central.

I wasn't aware of this library yet, probably because it was created in 2016. When I did an investigation on HMM libraries last year, I found some libraries but no library with a suitable license (Apache 2.0, BSD or similar) and with support for time-inhomogeneous Markov processes (i.e. with support for different states and transition probabilities at each time step), which is needed for map matching.

**Comment by stefanholder** [comment]
I just published version 0.2.1-SNAPSHOT on a Maven repository that is located on the mvn-repo branch of this GitHub repository.

The hmm-lib can now be added as a Maven dependency:

```
<dependency>
    <groupId>com.bmw.hmm_lib</groupId>
    <artifactId>hmm-lib</artifactId>
    <version>0.2.1-SNAPSHOT</version>
</dependency>
```

Moreover, the following repository needs to be added to the pom.xml:

```
<repository>
    <id>hmm-lib-mvn-repo</id>
    <url>https://raw.github.com/bmwcarit/hmm-lib/mvn-repo/</url>
    <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
    </snapshots>
</repository>        
```

Please let me know if this works. Once everything works fine, I will publish the final version 0.2.1 including jars for sources and javadoc.

**UPDATE**: The Maven repository https://raw.github.com/bmwcarit/hmm-lib/mvn-repo/ has been deleted. For snapshots, please use https://raw.github.com/bmwcarit/hmm-lib/mvn-snapshots/ instead (see also [README.md](https://github.com/bmwcarit/hmm-lib/blob/master/README.md)).

**Comment by karussell** [comment]
Thanks!

Hmmh, I'm not 100% sure but potentially we get problems when we release our map matching component to maven central then. See http://central.sonatype.org/pages/requirements.html _In addition we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts._

**Comment by stefanholder** [comment]
I'm still trying to get approval for publishing the hmm-lib to the Maven Central repository but this may take one or two more weeks.

When I tried to to use the hmm-lib from the github Maven Repository in graphhopper matching-core, I got compilation errors because the method [MostLikelySequence.getBrokenTimeStep()](https://github.com/graphhopper/map-matching/blob/master/hmm-lib/src/main/java/de/bmw/hmm/MostLikelySequence.java#L71) was added to the hmm-lib module in graphhopper map-matching. This method is used [here](https://github.com/graphhopper/map-matching/blob/master/matching-core/src/main/java/com/graphhopper/matching/MapMatching.java#L252). Do you want to create a pull request for this?

**Comment by karussell** [comment]
Yes, sure. Will do when I upgrade to the latest hmm-lib version (hopefully next week)

**Comment by karussell** [comment]
I've added PR #5 regarding the missing method, also I've added a [new branch](https://github.com/graphhopper/map-matching/tree/external-hmm-lib) which uses this 'external' hmm-lib

**Comment by stefanholder** [comment]
For hmm-lib 1.0.0, I changed the GitHub Maven repository location (there will be separate repositories for snapshots and releases). 1.0.0-SNAPSHOT can now be used via Maven as described [here](https://github.com/bmwcarit/hmm-lib/tree/branch-1.0#maven).

**Comment by stefanholder** [comment]
I still don't have approval for publishing the hmm-lib to the Maven Central repository, so you should rather assume that this won't happen.

@karussell: I would like to remove https://raw.github.com/bmwcarit/hmm-lib/mvn-repo/ with 0.2.1-SNAPSHOT since snapshots are now deployed to https://raw.github.com/bmwcarit/hmm-lib/mvn-snapshots/. Is this OK for you (the [external-hmm-lib branch](https://github.com/graphhopper/map-matching/tree/external-hmm-lib) still uses this)?

**Comment by karussell** [comment]
Ok, and yes, this removal should be no problem.
